I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 37, in script
    python:
  File "game/script.rpy", line 38, in <module>
    time.sleep(1000)
NameError: name 'time' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 37, in script
    python:
  File "/opt/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/opt/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 38, in <module>
    time.sleep(1000)
NameError: name 'time' is not defined

Linux-5.14.0-362.13.1.el9_3.x86_64-x86_64-with-glibc2.34 x86_64
Ren'Py 8.1.3.23091805
Lost_RI 1.0
Tue Jan 30 14:31:41 2024
